# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
- type: webfuzzsub
  options:
    url: https://t.me/s/ssrv2taytgshare?before=743
- type: webfuzzsub
  options:
    url: https://github.com/umelabs/node.umelabs.dev
- type: webfuzzsub
  options:
    url: https://github.com/freefq/free
- type: webfuzzsub
  options:
    url: https://github.com/oouxx/fqsub/blob/7f35b272888341f207acc10c92f1eb0be431e0e3/sub.list
- type: webfuzzsub
  options:
    url: https://lisondawang.tk/jiedianfenxiang.html



# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://rss.cnrss.xyz/link/RRbIrEn90XWdWQl5?mu=2
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/hotsymbol/vpnsetting/master/v2rayopen
- type: subscribe
  options:
    url: https://iwxf.netlify.app/
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app/
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0411.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/RaymondHarris971/ssrsub/master/9a075bdee5.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
    
    
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://github.com/freefq/free
- type: webfuzz
  options:
    url: https://github.com/iwxf/free-v2ray/blob/master/README.md
- type: webfuzz
  options:
    url: https://github.com/hugetiny/awesome-vpn/blob/master/READMECN.md
- type: webfuzz
  options:
    url: https://github.com/umelabs/node.umelabs.dev
- type: webfuzz
  options:
    url: https://github.com/ruanfei/ShadowsocksRRShare/blob/master/vmess%E8%8A%82%E7%82%B9%EF%BC%88%E9%A1%B6%E9%83%A8%E6%9C%80%E6%96%B0).md
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/
- type: webfuzz
  options:
    url: https://fanqiang.network/free-v2ray
- type: webfuzz
  options:
    url: https://www.freefq.com/d/file/free-ssr/20200811/1f3e9d0d0064f662457062712dcf1b66.txt
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ss/ss.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ssr/ssr.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/all.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/52bp/52bp.github.io/master/freesite.html
- type: webfuzz
  options:
    url: https://telegra.ph/2020-10-3-10-02
- type: webfuzz
  options:
    url: https://lisondawang.tk/jiedianfenxiang.html
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7



# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: ssrtool
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: ssrshares
    num: 200
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 200
- type: tgchannel
  options:
    channel: ssrv2taytgshare
    num: 200
- type: tgchannel
  options:
    channel: TgProxies
    num: 200
- type: tgchannel
  options:
    channel: TG_Mtproxy_1
    num: 200
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200    
- type: tgchannel
  options:
    channel: daolis_miao
    num: 200
- type: tgchannel
  options:
    channel: vmesssr
    num: 200
- type: tgchannel
  options:
    channel: sphard
    num: 200
- type: tgchannel
  options:
    channel: pjzyj0
    num: 200
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 200
- type: tgchannel
  options:
    channel: flyingboat
    num: 200
- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 200
- type: tgchannel
  options:
    channel: gyjclub
    num: 200
- type: tgchannel
  options:
    channel: VPNFolder
    num: 200
- type: tgchannel
  options:
    channel: youmtp
    num: 200
- type: tgchannel
  options:
    channel: ssrkn
    num: 200
- type: tgchannel
  options:
    channel: abchz
    num: 200
- type: tgchannel
  options:
    channel: yg251153
    num: 200
- type: tgchannel
  options:
    channel: woyaofq
    num: 200
- type: tgchannel
  options:
    channel: wwx_com
    num: 200
- type: tgchannel
  options:
    channel: freessr4k
    num: 200
- type: tgchannel
  options:
    channel: ultrafreevpn
    num: 200
- type: tgchannel
  options:
    channel: VSshit
    num: 200
- type: tgchannel
  options:
    channel: InternetSSR
    num: 200
- type: tgchannel
  options:
    channel: baipiaodadui
    num: 200
- type: tgchannel
  options:
    channel: mtproxy666
    num: 200
- type: tgchannel
  options:
    channel: v2ray666
    num: 200
- type: tgchannel
  options:
    channel: freeVPNserv
    num: 200



# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-51-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html



# 翻墙党，后面的东西都无需修改
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=50&auth=0
    num: 200
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=2&auth=0
    num: 200
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=36&auth=0
    num: 200



# clash格式订阅链接 
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
